---
title: "wq_data"
author: "Luke Vawter"
date: "December 13, 2018"
output: html_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(eval=evaluate, cache=cache.me)
```

```{r}
wq.df <- file.path(url.root,
                   "WaterQuality",
                   "WaterQuality",
                   format(min(phyto.df$sampledate) - days(3), "%m-%d-%Y"),
                   format(max(phyto.df$sampledate) + days(3), "%m-%d-%Y"), 
                   "6",
                   "7,16,23,24",
                   "station",
                   paste(station.vec, collapse = ","),
                   "21,34,74,83") %>% 
  fromJSON() %>% 
  clean_up() %>%
  filter(is.na(problem),
         parameter %in% c("chla", "doc", "pheo", "salinity"))
        
  
wq.df <- wq.df %>%
  select(station, sampledate, layer, depth, parameter, measurevalue) %>% #eventid,
  mutate(sampledate=as.Date(sampledate))
```

adds s_chla by changing those with pararmeter of chla and layer of surface to s_chla
(updated code so that it replaces the extracted chla with s_chla value):
```{r}
s_chla.df <- wq.df %>% 
  filter(layer == "s", 
         parameter == "chla") %>% 
  unite(parameter, c("layer", "parameter"), remove = FALSE) #%>% 
    
not_chla.df <- wq.df %>%
  filter(parameter != "chla") %>%
  bind_rows(s_chla.df)

chla_not_s_chla.df <- wq.df %>%
  filter(parameter == "chla") %>%
  filter(layer != "s") %>%
  bind_rows(not_chla.df)

wq.df <- chla_not_s_chla.df
```

```{r}
pdepth.df <- event.df %>% 
  filter(layer %in% c("ap", "wc")) %>% 
  mutate(sampledate = as.Date(sampledate)) %>% 
  select(station, sampledate, pdepth) %>% 
  dplyr::distinct()

wq.df <- left_join(wq.df, pdepth.df, by = c("station", "sampledate"))

```

filter out all below pycnocline values
```{R}
wq_test.df <- wq.df %>%
  filter(as.double(depth) <= as.double(pdepth)) #%>%

```

to work with Zach's 3 day window code
```{r eval=FALSE}
wq.df <- wq.df %>%
  rename(date = sampledate)

```


```{r}
data.table::fwrite(wq.df, file.path(project.dir, "data/water_quality", "cedr_wq.csv"))

wq.raw <- data.table::fread(file.path(project.dir, "data/water_quality/cedr_wq.csv"),
                            data.table = FALSE,
                           na.strings = c("")) #%>% 
  # filter(is.na(problem),
  #        parameter %in% c("chla", "doc", "pheo", "salinity"))

```

         